services:
  server:
    build: ./server
    ports:
      - '4500:4500'
    environment:
      - PORT=4500
      - CLIENT_URL=http://localhost:8080

  client:
    build:
      context: ./client
      args:
        VITE_SOCKET_URL: http://localhost:4500
    ports:
      - '8080:80'
    depends_on:
      - server
